---
apiVersion: v1
kind: Namespace
metadata:
 name: supervision
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-supervision
  namespace: supervision
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: supervision
  name: supervision
rules:
- apiGroups: [""] 
  resources: ["*"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions"] 
  resources: ["*"]
  verbs: ["get", "watch", "list"]  
- apiGroups: ["apps"] 
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-service-supevision
  namespace: supervision
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: supervision
subjects:
- kind: ServiceAccount
  name: service-supervision
  namespace: supervision
